saan-market/Controllers/BuyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace saan_market.Controllers
{
    public class BuyController : Controller
    {
        public ActionResult checkout_1()
        {
            return View();
        }
        public ActionResult checkout_2()
        {
            return View();
        }
        public ActionResult checkout_3()
        {
            return View();
        }
        public ActionResult checkout_4()
        {
            return View();
        }


        public ActionResult factor()
        {
            return View();
        }
    }
}

saan-market/Views/Buy/Factor.cshtml
@{
    ViewBag.Title = "فاکتور خرید";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<br />
<br />
<body>
    <div marginwidth="0" marginheight="0" dir="rtl" style="padding:0;margin:0;color:#3c3c3c;font-family:Tahoma">
        <center>
            <table width="70%" cellpadding="5" align="center" style="border-top:#ed1b2f 5px solid;border-bottom:#3c3c3c 5px solid">
                <tbody>
                    <tr>
                        <td>
                            <table width="98%" align="center" cellspacing="0" cellpadding="3" border="0" dir="rtl" style="padding:15px">
                                <tbody>
                                    <tr>
                                        <td align="center" style="font-size:24px;vertical-align:middle;font-family:Times new roman;font-weight:bold;width:100%">فاکتور خرید کالا</td>
                                    </tr>
                                </tbody>
                            </table>
                            <table width="98%" align="center" cellspacing="0" cellpadding="0" border="0" dir="rtl" style="font-size:11px">
                                <tbody>
                                    <tr>
                                        <td style="width:75%;vertical-align:top;text-align:right">
                                            <div style="border:1px solid #3c3c3c;border-radius:5px;margin-left:8px">
                                                <table width="100%" align="center" cellspacing="0" cellpadding="0" border="0" dir="rtl" style="height:99px">
                                                    <tbody>
                                                        <tr>
                                                            <td rowspan="3" style="width:7%;vertical-align:middle" />
                                                            <td style="width:50%;padding-right:10px">
                                                                <span style="font-weight:bold">خریدار : </span>سعید ژیانی
                                                            </td>
                                                            <td style="width:43%">
                                                                <span style="font-weight:bold">شماره ملی : </span>0123456789
                                                            </td>
                                                        </tr>
                                                        <tr>
                                                            <td colspan="4" style="padding-right:10px">
                                                                <span style="font-weight:bold">آدرس : </span>
                                                                تهران
                                                            </td>
                                                        </tr>
                                                        <tr>
                                                            <td style="min-width:50%;padding-right:10px">
                                                                <span style="font-weight:bold">شماره تماس : </span>09331234567
                                                            </td>
                                                            <td colspan="3">
                                                                <span style="font-weight:bold">کدپستی : </span>0123456789
                                                            </td>
                                                        </tr>
                                                    </tbody>
                                                </table>
                                            </div>
                                        </td>
                                        <td style="width:25%;vertical-align:top;text-align:right">
                                            <div style="border:1px solid #3c3c3c;border-radius:5px">
                                                <table width="100%" align="center" cellspacing="0" cellpadding="0" dir="rtl" style="height:99px">
                                                    <tbody>
                                                        <tr>
                                                            <td style="font-size:11px;height:25px;padding:0 15px;font-weight:bold">تاریخ : </td>
                                                            <td>1394/7/27</td>
                                                        </tr>
                                                        <tr>
                                                            <td style="font-size:11px;height:25px;padding:0 15px;font-weight:bold">شماره پیگیری : </td>
                                                            <td>ABC-6416867</td>
                                                        </tr>
                                                        <tr>
                                                            <td style="font-size:11px;height:25px;padding:0 15px;font-weight:bold">کد مشتری : </td>
                                                            <td>2533674</td>
                                                        </tr>
                                                    </tbody>
                                                </table>
                                            </div>
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                            <br>
                            <table width="98%" align="center" cellspacing="0" cellpadding="0" dir="rtl" style="font-family:Tahoma;font-size:11px;text-align:center;border:1px solid #3c3c3c;">
                                <tbody>
                                    <tr style="background-color:#f0f0f0">
                                        <td style="border-bottom:1px solid #3c3c3c;padding:5px 0;width:30px">ردیف</td>
                                        <td style="border-right:1px solid #3c3c3c;padding:5px 0;border-bottom:1px solid #3c3c3c;width:60px">کد کالا</td>
                                        <td style="border-right:1px solid #3c3c3c;padding:5px 0;border-bottom:1px solid #3c3c3c;width:300px">شرح کالا</td>
                                        <td style="border-right:1px solid #3c3c3c;padding:5px 0;border-bottom:1px solid #3c3c3c;width:300px">توضیحات</td>
                                        <td style="border-right:1px solid #3c3c3c;padding:5px 0;border-bottom:1px solid #3c3c3c;width:35px">تعداد</td>
                                        <td style="border-right:1px solid #3c3c3c;padding:5px 0;border-bottom:1px solid #3c3c3c;width:60px">مبلغ واحد (ریال)</td>
                                        <td style="border-right:1px solid #3c3c3c;padding:5px 0;border-bottom:1px solid #3c3c3c;width:60px">مبلغ کل (ریال)</td>
                                        <td style="border-right:1px solid #3c3c3c;padding:5px 0;border-bottom:1px solid #3c3c3c;width:50px">تخفیف (ریال)</td>
                                        <td style="border-right:1px solid #3c3c3c;padding:5px 0;border-bottom:1px solid #3c3c3c;width:85px">مبلغ کل پس از تخفیف (ریال)</td>
                                    </tr>
                                    <tr>
                                        <td style="border-right:1px solid #3c3c3c;padding:5px 0;border-bottom:1px solid #3c3c3c">1</td>
                                        <td style="border-right:1px solid #3c3c3c;padding:5px 0;border-bottom:1px solid #3c3c3c">ABC-34012</td>
                                        <td style="border-right:1px solid #3c3c3c;padding:5px 0;border-bottom:1px solid #3c3c3c;text-align:right">Huawei Ascend P7 | مشکی | گارانتی 18 ماهه تک تیم فن +یک ماه تعویض (نماینده رسمی هوآوی در ایران)</td>
                                        <td style="border-right:1px solid #3c3c3c;padding:5px 0;border-bottom:1px solid #3c3c3c;text-align:right">&nbsp;</td>
                                        <td style="border-right:1px solid #3c3c3c;padding:5px 0;border-bottom:1px solid #3c3c3c">1</td>
                                        <td style="border-right:1px solid #3c3c3c;padding:5px 0;border-bottom:1px solid #3c3c3c">7,568,807</td>
                                        <td style="border-right:1px solid #3c3c3c;padding:5px 0;border-bottom:1px solid #3c3c3c">7,568,807</td>
                                        <td style="border-right:1px solid #3c3c3c;padding:5px 0;border-bottom:1px solid #3c3c3c">0</td>
                                        <td style="border-right:1px solid #3c3c3c;padding:5px 0;border-bottom:1px solid #3c3c3c">7,568,807</td>
                                    </tr>
                                    <tr>
                                        <td style="border-right:1px solid #3c3c3c;padding:5px 0;border-bottom:1px solid #3c3c3c">2</td>
                                        <td style="border-right:1px solid #3c3c3c;padding:5px 0;border-bottom:1px solid #3c3c3c">ABC-102305</td>
                                        <td style="border-right:1px solid #3c3c3c;padding:5px 0;border-bottom:1px solid #3c3c3c;text-align:right">Nillkin Amazing H Nano Anti-Burst Glass Screen Protector For Huawei Ascend P7 | بی رنگ شفاف | سرویس ویژه دیجی کالا: 7 روز تضمین تعویض کالا</td>
                                        <td style="border-right:1px solid #3c3c3c;padding:5px 0;border-bottom:1px solid #3c3c3c;text-align:right">&nbsp;</td>
                                        <td style="border-right:1px solid #3c3c3c;padding:5px 0;border-bottom:1px solid #3c3c3c">1</td>
                                        <td style="border-right:1px solid #3c3c3c;padding:5px 0;border-bottom:1px solid #3c3c3c">266,055</td>
                                        <td style="border-right:1px solid #3c3c3c;padding:5px 0;border-bottom:1px solid #3c3c3c">266,055</td>
                                        <td style="border-right:1px solid #3c3c3c;padding:5px 0;border-bottom:1px solid #3c3c3c">0</td>
                                        <td style="border-right:1px solid #3c3c3c;padding:5px 0;border-bottom:1px solid #3c3c3c">266,055</td>
                                    </tr>
                                    <tr>
                                        <td style="border-right:1px solid #3c3c3c;padding:5px 0;border-bottom:1px solid #3c3c3c">3</td>
                                        <td style="border-right:1px solid #3c3c3c;padding:5px 0;border-bottom:1px solid #3c3c3c">ABC-50309</td>
                                        <td style="border-right:1px solid #3c3c3c;padding:5px 0;border-bottom:1px solid #3c3c3c;text-align:right">Jelly Cover For Huawei Ascend P7 | بی رنگ | سرویس ویژه دیجی کالا: 7 روز تضمین تعویض کالا</td>
                                        <td style="border-right:1px solid #3c3c3c;padding:5px 0;border-bottom:1px solid #3c3c3c;text-align:right">&nbsp;</td>
                                        <td style="border-right:1px solid #3c3c3c;padding:5px 0;border-bottom:1px solid #3c3c3c">1</td>
                                        <td style="border-right:1px solid #3c3c3c;padding:5px 0;border-bottom:1px solid #3c3c3c">183,486</td>
                                        <td style="border-right:1px solid #3c3c3c;padding:5px 0;border-bottom:1px solid #3c3c3c">183,486</td>
                                        <td style="border-right:1px solid #3c3c3c;padding:5px 0;border-bottom:1px solid #3c3c3c">0</td>
                                        <td style="border-right:1px solid #3c3c3c;padding:5px 0;border-bottom:1px solid #3c3c3c">183,486</td>
                                    </tr>
                                    <tr style="background-color:#f0f0f0">
                                        <td colspan="4"></td>
                                        <td colspan="4" style="font-weight:bold;font-size:11px;border-right:1px solid #3c3c3c;border-top:1px solid #3c3c3c;height:30px">جمع مبلغ کل پس از تخفیف(ریال)</td>
                                        <td style="border-right:1px solid #3c3c3c;border-top:1px solid #3c3c3c">8,740,000</td>
                                    </tr>
                                </tbody>
                            </table>
                        </td>
                    </tr>
                </tbody>
            </table>
        </center>
    </div>
</body>

saan-market/Views/Buy/checkout_1.cshtml
@{
    ViewBag.Title = "بازبینی سبد خرید";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<br />
<br />
<div class="container">
    <div class="row">

        <!--  ==========  -->
        <!--  = Main content =  -->
        <!--  ==========  -->
        <section class="span12">

            <div class="checkout-container">
                <div class="row">
                    <div class="span10 offset1">

                        <!--  ==========  -->
                        <!--  = Header =  -->
                        <!--  ==========
                        <header>
                            <div class="row">
                                <div class="span2">
                                    <a href="index.html"><img src="images/logo-bw.png" alt="Webmarket Logo" width="48" height="48" /></a>
                                </div>
                                <div class="span6">
                                    <div class="center-align">
                                        <h1><span class="light">بازبینی</span> سبد خرید</h1>
                                    </div>
                                </div>
                                <div class="span2">
                                    <div class="right-align">

                                    </div>
                                </div>
                            </div>
                        </header>
                         -->
                        <!--  ==========  -->
                        <!--  = Steps =  -->
                        <!--  ==========  -->
                        <div class="checkout-steps">
                            <div class="clearfix">
                                <div class="step active">
                                    <div class="step-badge">1</div>
                                    سبد خرید
                                </div>
                                <div class="step">
                                    <div class="step-badge">2</div>
                                    آدرس ارسال
                                </div>
                                <div class="step">
                                    <div class="step-badge">3</div>
                                    شیوه پرداخت
                                </div>
                                <div class="step">
                                    <div class="step-badge">4</div>
                                    تایید و پرداخت
                                </div>
                            </div>
                        </div> <!-- /steps -->
                        <!--  ==========  -->
                        <!--  = Selected Items =  -->
                        <!--  ==========  -->
                        <table class="table table-items">
                            <thead>
                                <tr>
                                    <th colspan="2">آیتم</th>
                                    <th><div class="align-center">تعداد</div></th>
                                    <th><div class="align-right">قیمت</div></th>
                                </tr>
                            </thead>
                            <tbody>

                                <tr>
                                    <td class="image"><img src="~/Content/images/placeholder.png" alt="" width="124" height="124" /></td>
                                    <td class="desc">لباس ورزشی آدیداس &nbsp; <a title="Remove Item" class="icon-remove-sign" href="#"></a></td>
                                    <td class="qty">
                                        <input type="text" class="tiny-size" value="4" />
                                    </td>
                                    <td class="price">
                                        $59
                                    </td>
                                </tr>


                                <tr>
                                    <td colspan="2" rowspan="2"></td>
                                    <td class="stronger">هزینه ارسال :</td>
                                    <td class="stronger"><div class="align-right">$4.99</div></td>
                                </tr>
                                <tr>
                                    <td class="stronger">جمع کل :</td>
                                    <td class="stronger"><div class="size-16 align-right">$357.81</div></td>
                                </tr>
                            </tbody>
                        </table>

                        <hr />

                        <p class="right-align">
                            در مرحله بعدی شما آدرس ارسال را انتخاب خواهید کرد. &nbsp; &nbsp;
                            <a href="@Url.Action("checkout_2", "Buy")" class="btn btn-primary higher bold">ادامه</a>
                        </p>
                    </div>
                </div>
            </div>


        </section> <!-- /main content -->

    </div>
</div> <!-- /container -->

saan-market/Views/Buy/checkout_3.cshtml
@{
    ViewBag.Title = "انتخاب شیوه پرداخت";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<br />
<br />

<div class="container">
    <div class="row">

        <!--  ==========  -->
        <!--  = Main content =  -->
        <!--  ==========  -->
        <section class="span12">

            <div class="checkout-container">
                <div class="row">
                    <div class="span10 offset1">

                        <!--  ==========  -->
                        <!--  = Header =  -->
                        <!--  ==========
                        <header>
                            <div class="row">
                                <div class="span2">
                                    <a href="index.html"><img src="images/logo-bw.png" alt="Webmarket Logo" width="48" height="48" /></a>
                                </div>
                                <div class="span6">
                                    <div class="center-align">
                                        <h1><span class="light">انتخاب</span> شيوه پرداخت</h1>
                                    </div>
                                </div>
                                <div class="span2">
                                    <div class="right-align">
                                    </div>
                                </div>
                            </div>
                        </header>

                        <!--  ==========  -->
                        <!--  = Steps =  -->
                        <!--  ==========  -->
                        <div class="checkout-steps">
                            <div class="clearfix">
                                <div class="step done">
                                    <div class="step-badge"><i class="icon-ok"></i></div>
                                    @Html.ActionLink("سبد خرید", "checkout_1", "Buy")
                                </div>
                                <div class="step done">
                                    <div class="step-badge"><i class="icon-ok"></i></div>
                                    @Html.ActionLink("آدرس ارسال", "checkout_2", "Buy")
                                </div>
                                <div class="step active">
                                    <div class="step-badge">3</div>
                                    شيوه پرداخت
                                </div>
                                <div class="step">
                                    <div class="step-badge">4</div>
                                    تاييد و پرداخت
                                </div>
                            </div>
                        </div> <!-- /steps -->
                        <!--  ==========  -->
                        <!--  = Payment =  -->
                        <!--  ==========  -->
                        <div class="shifted-left-45 clearfix">
                            <h3 class="no-margin"><span class="light">کارت</span> اعتباري</h3>
                            <p class="push-down-30">کارت های عضو شتاب قابل قبول هستند.</p>

                            <form action="#" method="post" class="form-horizontal form-checkout">
                                <div class="control-group">
                                    <label class="control-label" for="firstName">نام<span class="red-clr bold">*</span></label>
                                    <div class="controls">
                                        <input type="text" id="firstName" class="span4" required>
                                    </div>
                                </div>
                                <div class="control-group">
                                    <label class="control-label" for="lastName">نام خانوادگي<span class="red-clr bold">*</span></label>
                                    <div class="controls">
                                        <input type="text" id="lastName" class="span4" required>
                                    </div>
                                </div>
                                <div class="control-group">
                                    <label class="control-label" for="cardNum">شماره کارت اعتباري<span class="red-clr bold">*</span></label>
                                    <div class="controls">
                                        <input type="text" id="cardNum" class="span1 card-num-input center-align" maxlength="4">
                                        <input type="text" class="span1 card-num-input center-align" maxlength="4">
                                        <input type="text" class="span1 card-num-input center-align" maxlength="4">
                                        <input type="text" class="span1 card-num-input center-align add-tooltip" maxlength="4" />
                                    </div>
                                    <!-- class="span1 card-num-input center-align add-tooltip" maxlength="4" >
                                    -->

                                </div>
                                <div class="control-group">
                                    <label class="control-label" for="cvc">CVC or CVS<span class="red-clr bold">*</span></label>
                                    <div class="controls">
                                        <input id="cvc" type="text" class="span1 center-align add-tooltip" maxlength="3" required>
                                    </div>
                                    <!-- class="span1 center-align add-tooltip" data-title="سه یا چهار رقم آخر نوشته شده بر پشت کارت">
                                    -->

                                </div>
                                <div class="control-group">
                                    <label class="control-label" for="exp">تاريخ انقضا<span class="red-clr bold">*</span></label>
                                    <div class="controls">
                                        <select id="exp" class="input-small month-push-right">
                                            <option value="-1">ماه</option>
                                            <option value="1">01</option>
                                            <option value="2">02</option>
                                            <option value="3">03</option>
                                            <option value="4">04</option>
                                            <option value="5">05</option>
                                            <option value="6">06</option>
                                            <option value="7">07</option>
                                            <option value="8">08</option>
                                            <option value="9">09</option>
                                            <option value="10">10</option>
                                            <option value="11">11</option>
                                            <option value="12">12</option>

                                        </select>
                                        <select id="exp" class="input-small">
                                            <option value="-1">سال</option>
                                            <option value="1394">1394</option>
                                            <option value="1395">1395</option>
                                            <option value="1396">1396</option>
                                            <option value="1397">1397</option>
                                            <option value="1398">1398</option>
                                            <option value="1399">1399</option>

                                        </select>
                                    </div>
                                </div>
                            </form>
                        </div>

                        <hr />

                        <p class="right-align">
                            در مرحله بعدي شما قادر هستيد سفارشتان را بازبيني کرده و آن را تاييد کنيد &nbsp; &nbsp;
                            <a href="@Url.Action("checkout_4", "Buy")" class="btn btn-primary higher bold">ادامه</a>
                        </p>


                    </div>
                </div>
            </div>


        </section> <!-- /main content -->

    </div>
</div> <!-- /container -->

saan-market/Views/Buy/checkout_4.cshtml
@{
    ViewBag.Title = "تایید و پرداخت";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<br />
<br />


<div class="container">
    <div class="row">

        <!--  ==========  -->
        <!--  = Main content =  -->
        <!--  ==========  -->
        <section class="span12">

            <div class="checkout-container">
                <div class="row">
                    <div class="span10 offset1">

                        <!--  ==========  -->
                        <!--  = Header =  -->
                        <!--  ==========
                        <header>
                            <div class="row">
                                <div class="span2">
                                    <a href="index.html"><img src="images/logo-bw.png" alt="Webmarket Logo" width="48" height="48" /></a>
                                </div>
                                <div class="span6">
                                    <div class="center-align">
                                        <h1><span class="light">تاييد</span> و پرداخت</h1>
                                    </div>
                                </div>
                                <div class="span2">
                                    <div class="right-align">
                                    </div>
                                </div>
                            </div>
                        </header>

                        <!--  ==========  -->
                        <!--  = Steps =  -->
                        <!--  ==========  -->
                        <div class="checkout-steps">
                            <div class="clearfix">
                                <div class="step done">
                                    <div class="step-badge"><i class="icon-ok"></i></div>
                                    @Html.ActionLink("سبد خرید", "checkout_1", "Buy")
                                </div>
                                <div class="step done">
                                    <div class="step-badge"><i class="icon-ok"></i></div>
                                    @Html.ActionLink("آدرس ارسال", "checkout_2", "Buy")
                                </div>
                                <div class="step done">
                                    <div class="step-badge"><i class="icon-ok"></i></div>
                                    @Html.ActionLink("شیوه پرداخت", "checkout_3", "Buy")
                                </div>
                                <div class="step active">
                                    <div class="step-badge">4</div>
                                    تاييد و پرداخت
                                </div>
                            </div>
                        </div> <!-- /steps -->
                        <!--  ==========  -->
                        <!--  = Selected Items =  -->
                        <!--  ==========  -->
                        <table class="table table-items">
                            <thead>
                                <tr>
                                    <th colspan="2">آيتم</th>
                                    <th><div class="align-center">تعداد</div></th>
                                    <th><div class="align-right">قيمت</div></th>
                                </tr>
                            </thead>
                            <tbody>

                                <tr>
                                    <td class="image"><img src="~/Content/images/placeholder.png" alt="" width="124" height="124" /></td>
                                    <td class="desc">لباس ورزشي آديداس</td>
                                    <td class="qty">
                                        3
                                    </td>
                                    <td class="price">
                                        $59
                                    </td>
                                </tr>

                                <tr>
                                    <td colspan="2" rowspan="2">
                                        &nbsp;
                                    </td>
                                    <td class="stronger">هزينه ارسال :</td>
                                    <td class="stronger"><div class="align-right">$4.99</div></td>
                                </tr>
                                <tr>
                                    <td class="stronger">جمع کل :</td>
                                    <td class="stronger"><div class="size-16 align-right">$357.81</div></td>
                                </tr>
                            </tbody>
                        </table>

                        <p class="right-align">
                            <a href="@Url.Action("Index", "Home")" class="btn btn-primary higher bold">تاييد و پرداخت</a>
                        </p>
                    </div>
                </div>
            </div>


        </section> <!-- /main content -->

    </div>
</div> <!-- /container -->